import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import ExcludeWrapper from "@/components/ExcludeWrapper/ExcludeWrapper";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/NavBar/NavBar";
import { AuthProvider } from "@/context/AuthContext"; // 👈 IMPORTANTE


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {/* 👇 EL CONTEXTO ENVUELVE TODA LA APP */}
        <AuthProvider>
          <div className="flex flex-col min-h-screen">
            <ExcludeWrapper>
              <Navbar />
            </ExcludeWrapper>

            <main className="flex-grow">
              {children}
            </main>

            <Footer />
          </div>
        </AuthProvider>

      </body>
    </html>
  );
}
